services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: Orren-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./apps/backend/app:/app/app
    restart: unless-stopped
